os:
  - linux
  - windows
dist: xenial
language: rust
rust:
- nightly
script:
- source ci/build.sh
before_install:
- source ci/before_install.sh
deploy:
  skip_cleanup: true
  provider: script
  script: bash ci/deploy.sh
  on:
    branch: master
notifications:
  pushover:
    api_key:
      secure: jbFBfE9scdZQg+WQkgn41TK90Rl1WVotfXYy+rxQtws1YMX5kQh1Tg441ZCOi1oVwxDv7dZ7hu+4mYu06sgJ/5aEesSaboxbflfsYe8+QNRUna3201ElrtqmqLiz6y9trq6zLSsIzmJB40A/6pBJ/wGYzjsQXz/Dj2vMgb6kAL/zZIy4Z75oXeqOaM0efjr2iJI0175aHKDApfcSgcnJM7ZiW260EpoBPDvmhmCTgymqHOieMW+jzoeya2N+Q6Ij93TXRJM1BdmfrrcIE2L4tmJ300qBkqqi/22HhkE3u+I6MCpggXmWMRi59cDqlWveyGfdUltM0zULxKjBA0Igrtih207gnhmOhaUSPKPSAzLnalZkNk6Dfn8M5qATH1V4RcolptqGV5WpS2dzO6TBLC95gRYySwT6USBjqpOKRdQdjxRRiJ0kSNMvjhrrTpyrA7eWIP3qsMt6OliIHZkG35lO327WDwDxkSRxqJdRLz9pTrxS6W3kwteTFPiSSKEey8LO4hmRGjJqIjblAiZ10o2tPm7cUVu6yHOl0TcDxBs1nx4IPTCLLriB0712HCY9c/jTW2F5ybPBwwRJ77mKjVRoIKhrT7RGqruPv3ZGnB7qL2ehOLDJDtFCB7op5jfKz5pTqya5lBXZ1atS66vwNhF8aCfp5YSiscReWQG0Eco=
    users:
      secure: xWC+wFgxYfKbtNiSqNpBKNLV9cR4+sLH3hKpdN7DSWOnW8mMJcDIw/YH72Rvih7XThldK1sHDq59Z55Hjxeeq8tHU04bgM0A3PfLxBZsSUY/gDmzlj84ZmE1rcbQqaW0buq9ifXWgXlBHrckzhb7kLU4trRiFrF+NL4dAa3xU4+x5gmYzykeWKg0sU9y6FAkdHiJ0jFf1nPLV8fpYCIWr+MZRK9m5BTVZv6w6wRp6TeoOoAIlwLrJEPVbx9rMIbqAyRs8Yp6jk00OCS3b+IplTBvbZ/n3BQh+xkRZ5DYN/sixnxzN9MA6MD5guNVqHDQka5DE34kCvqTJ0ntl1pON8rGBLKzanQPQQVngoVHQj1enPkiBzVV131myWI1Uul7fbbwnOZF+EIzkkcXvHRpFNNaHteNCA6gvfGVKFvq+cvqRsWICBEz27W+AoNeGonmBmS9AHIHtvlTGa6EAgKJ7XKWSw33zBPp3l57GRo95GxfTeeKwflsJbuBYAcTYGuGqByCmUA+/SJwdSBRp+uHQxiwll8sjbTuktB8ZSIBDppigvQE/T7fQlZl6Awi/4O5oS5Zpv28CnDjw6E1gFdiUaM6XISmLgEV/nAz+ZcL1gLQ+QdyuoBZOFhd+ruGs61+2K7nPdAMU+9nWsABvHNTnsMYw9h0Yz3Fj1umIy0k5AA=
