dist: xenial
language: rust
rust:
- nightly-2019-04-07
script:
- cargo build --verbose --all
- cargo test --verbose --all
- cargo build --verbose --release --all
before_install:
- openssl aes-256-cbc -K $encrypted_68d9c3eaf1da_key -iv $encrypted_68d9c3eaf1da_iv
  -in travis.enc -out travis -d
- eval "$(ssh-agent -s)"
- echo -e "Host $DEPLOY_TO\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 ./travis
- ssh-add travis
deploy:
  skip_cleanup: true
  provider: script
  script: bash server_deployment/deploy.sh
  on:
    branch: master
