[package]
name = "server_rs"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

[dependencies]
log = "*"
env_logger = "*"
osm_api = {path="../osm_api"}
osm_db = {path="../osm_db"}