[package]
name = "osm_db"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

[dependencies]
osm_api = {path = "../osm_api"}
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
lazy_static = "*"
linked-hash-map = {version = "*", features = ["serde_impl"]}
log = "*"
uom = "*"