[package]
name = "osm_db"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

[dependencies]
osm_api = {path = "../osm_api"}
serde = {version="*", features=["derive"]}
serde_json = "*"
serde_yaml = "*"
lazy_static = "*"
linked-hash-map = {version = "*", features = ["serde_impl"]}
log = "*"
uom = "*"
rusqlite = {"version" = "*", "features" = ["bundled-windows", "load_extension"]}
thiserror = "*"
hashbrown = {version="*", features=["serde"]}
dirs = "*"
base64 = "*"